[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
foo = "9zKj7KkRHEjUtzBbF93sCdvJNhDug92959urdnGJHnw4"
counter = "FhE3gjEUVe6K56NYkHK8et1ifZQTkvB1h1Zy42Mk5cSd"
favour = "AGfatHL8AvqujDFVqWJcoQojPza1bznfrQDGyXB2XUna"

[programs.localnet]
foo = "9zKj7KkRHEjUtzBbF93sCdvJNhDug92959urdnGJHnw4"
counter = "FhE3gjEUVe6K56NYkHK8et1ifZQTkvB1h1Zy42Mk5cSd"
favour = "AGfatHL8AvqujDFVqWJcoQojPza1bznfrQDGyXB2XUna"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
